### ISSUE TITLE
Make embedded package

### ISSUE THREAD

**Issue by majkinetor** [StefanScherer/choco-mkcert#4]
As you know there are all sorts of problems with non-embedded packages. 

See [this](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#114-embed-a-package-if-allowed) link for details.

**Comment by StefanScherer** [comment]
Nice idea, but I don't want to embed the software. I do not really know any public choco package that does this.

**Comment by majkinetor** [comment]
See this [report](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f) from core choco repository. Packages marked with  &#x1F4E5; are embedded which is almost all of them.

**Comment by StefanScherer** [comment]
Thanks, I didn't know that.
I had a look at the license of mkcert which is BSD-3. 
I still don't want to make the effort changing the pipeline, checking if the license is fully covered, especially https://github.com/FiloSottile/mkcert/blob/a177c7e2ad5e8b056ec565de648ee61a27373310/LICENSE#L9-L12.

But the pipeline to build the package is here in this repo so it can be changed, eg. with a pull request if you want to help me. :-)

**Comment by majkinetor** [comment]
Could you add me as maintainer and I will migrate this package to my own repository and do it  ?

**Comment by StefanScherer** [comment]
Sure, thanks for helping out.

**Comment by majkinetor** [comment]
I will let you know when it is done. Not sure when tho, I just had LASIK and can't use computer extensively in the near future. You can continue with eventual updates until then. After that it will have automatic AU updater and it will live its own life.
